"use client";

import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useMemo, useState } from "react";

const products = [{ id: "latte", name: "Latte", category: "Coffee", price: 120 }, { id: "americano", name: "Americano", category: "Coffee", price: 90 }, { id: "sandwich", name: "Sandwich", category: "Food", price: 150 }, { id: "water", name: "Water", category: "Drinks", price: 40 }] as const;
const methods = ["Cash", "Card", "GCash", "Maya"] as const;
type Id = (typeof products)[number]["id"];
type View = "cart" | "payment" | "receipt";
const peso = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 0 });

export function InteractivePosDemo() {
  const [cart, setCart] = useState<Record<Id, number>>({ latte: 0, americano: 0, sandwich: 0, water: 0 });
  const [view, setView] = useState<View>("cart");
  const [method, setMethod] = useState<(typeof methods)[number]>("Cash");
  const reduceMotion = useReducedMotion();
  const items = useMemo(() => products.map((item) => ({ ...item, quantity: cart[item.id] })).filter((item) => item.quantity), [cart]);
  const total = useMemo(() => items.reduce((sum, item) => sum + item.price * item.quantity, 0), [items]);
  const count = useMemo(() => items.reduce((sum, item) => sum + item.quantity, 0), [items]);
  const add = (id: Id) => setCart((current) => ({ ...current, [id]: current[id] + 1 }));
  const remove = (id: Id) => setCart((current) => ({ ...current, [id]: Math.max(0, current[id] - 1) }));
  const restart = () => { setCart({ latte: 0, americano: 0, sandwich: 0, water: 0 }); setMethod("Cash"); setView("cart"); };
  const enter = reduceMotion ? false : { opacity: 0, y: 8 };
  return <section id="interactive-demo" className="bg-stone-950 py-20 text-white sm:py-24 lg:py-28"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12">
    <div className="mx-auto max-w-[780px] text-center"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-300">Try the flow</p><h2 className="mt-4 text-balance text-4xl font-extrabold tracking-[-0.055em] sm:text-5xl">Feel how simple checkout can be.</h2><p className="mx-auto mt-5 max-w-[660px] text-pretty text-lg leading-7 text-stone-300">Add a product, review the cart, choose a payment method, and finish the sale. This is a visual product demo only and does not process real payments.</p></div>
    <div className="mx-auto mt-12 max-w-[1180px] overflow-hidden rounded-[24px] border border-white/10 bg-[#11110f] shadow-[0_32px_100px_rgba(0,0,0,0.42)]"><div className="flex min-h-12 items-center justify-between border-b border-white/10 px-4 sm:px-5"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-600 text-[11px] font-black">T</span><div><p className="text-xs font-bold">TINDIO POS Demo</p><p className="text-[10px] text-stone-400">Main Register</p></div></div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-2.5 py-1 text-[10px] font-bold text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />ONLINE</span></div>
      <AnimatePresence mode="wait" initial={false}>{view === "cart" && <motion.div key="cart" initial={enter} animate={{ opacity: 1, y: 0 }} exit={reduceMotion ? undefined : { opacity: 0, y: -8 }} transition={{ duration: reduceMotion ? 0 : .22 }} className="grid lg:grid-cols-[1.15fr_.85fr]"><div className="border-b border-white/10 p-4 sm:p-6 lg:border-b-0 lg:border-r"><div className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm text-stone-400">Search products, SKU, or scan barcode</div><div className="mt-4 flex gap-2">{["Catalogue", "Favorites", "Recent"].map((label, index) => <span key={label} className={`rounded-lg px-3 py-2 text-xs font-bold ${index === 0 ? "bg-emerald-600" : "border border-white/10 text-stone-300"}`}>{label}</span>)}</div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-2 xl:grid-cols-4">{products.map((product) => <button key={product.id} type="button" onClick={() => add(product.id)} className="rounded-xl border border-white/10 bg-white/[.04] p-4 text-left transition hover:-translate-y-0.5 hover:border-emerald-400/40 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-400"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10 text-sm font-extrabold text-emerald-300">{product.name[0]}</span><p className="mt-5 text-sm font-bold">{product.name}</p><p className="mt-1 text-xs text-stone-500">{product.category}</p><p className="mt-3 text-base font-extrabold">{peso.format(product.price)}</p></button>)}</div></div>
        <div className="bg-white/[.025] p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.1em] text-stone-500">Current cart</p><p className="mt-1 text-lg font-extrabold">{count ? `${count} ${count === 1 ? "item" : "items"}` : "No items yet"}</p><div className="mt-5 min-h-48">{items.length ? <ul className="divide-y divide-white/10">{items.map((item) => <li key={item.id} className="flex items-center justify-between gap-3 py-3.5"><div><p className="text-sm font-bold">{item.name}</p><p className="mt-1 text-xs text-stone-500">{peso.format(item.price)} each</p></div><div className="flex items-center gap-2"><button type="button" aria-label={`Remove one ${item.name}`} onClick={() => remove(item.id)} className="h-8 w-8 rounded-lg border border-white/10 focus-visible:outline-2 focus-visible:outline-emerald-400">−</button><span className="w-5 text-center text-sm font-bold">{item.quantity}</span><button type="button" aria-label={`Add one ${item.name}`} onClick={() => add(item.id)} className="h-8 w-8 rounded-lg border border-white/10 focus-visible:outline-2 focus-visible:outline-emerald-400">+</button></div></li>)}</ul> : <div className="flex min-h-48 items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/10 p-6 text-center text-sm font-bold text-stone-300">Add something from the catalogue.</div>}</div><div className="mt-5 border-t border-white/10 pt-5"><p className="text-xs text-stone-500">Total</p><p className="mt-1 text-3xl font-extrabold tracking-[-.05em]">{peso.format(total)}</p><button type="button" disabled={!total} onClick={() => setView("payment")} className="mt-5 flex min-h-12 w-full justify-between rounded-xl bg-emerald-600 px-4 text-sm font-extrabold disabled:cursor-not-allowed disabled:bg-stone-800 disabled:text-stone-500 focus-visible:outline-2 focus-visible:outline-emerald-400"><span>Charge</span><span>{peso.format(total)}</span></button></div></div></motion.div>}
      {view === "payment" && <motion.div key="payment" initial={reduceMotion ? false : { opacity: 0, scale: .985 }} animate={{ opacity: 1, scale: 1 }} className="mx-auto w-full max-w-[760px] p-5 sm:p-8 lg:p-10"><button type="button" onClick={() => setView("cart")} className="text-sm font-semibold text-stone-400 focus-visible:outline-2 focus-visible:outline-emerald-400">← Back to cart</button><div className="mt-8 text-center"><p className="text-xs font-bold uppercase tracking-[.12em] text-stone-500">Sale total</p><p className="mt-2 text-5xl font-extrabold tracking-[-.07em]">{peso.format(total)}</p><p className="mt-3 text-sm text-stone-400">Choose how this demo sale is paid.</p></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{methods.map((item) => <button key={item} type="button" onClick={() => setMethod(item)} className={`min-h-20 rounded-xl border p-4 text-sm font-extrabold focus-visible:outline-2 focus-visible:outline-emerald-400 ${method === item ? "border-emerald-400 bg-emerald-400/10 text-emerald-200" : "border-white/10 text-stone-300"}`}>{item}</button>)}</div><button type="button" onClick={() => setView("receipt")} className="mt-8 min-h-12 w-full rounded-xl bg-emerald-600 px-5 text-sm font-extrabold focus-visible:outline-2 focus-visible:outline-emerald-400">Complete demo payment</button></motion.div>}
      {view === "receipt" && <motion.div key="receipt" initial={enter} animate={{ opacity: 1, y: 0 }} className="mx-auto w-full max-w-[620px] p-5 sm:p-8 lg:p-10"><div className="rounded-[20px] border border-white/10 bg-white/[.04] p-5 text-center sm:p-7"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500/15 text-2xl text-emerald-300">✓</div><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-emerald-300">Payment complete</p><h3 className="mt-2 text-3xl font-extrabold">{peso.format(total)}</h3><p className="mt-2 text-sm text-stone-400">Paid with {method}</p><button type="button" onClick={restart} className="mt-6 min-h-11 rounded-xl border border-white/15 px-5 text-sm font-bold focus-visible:outline-2 focus-visible:outline-emerald-400">Restart demo</button></div></motion.div>}</AnimatePresence>
    </div></div></section>;
}
